esphome:
  name: rfreceivertest
  friendly_name: RFReceivertest

esp32:
  board: esp32dev
  framework:
    type: arduino

switch:
  - platform: gpio
    pin: 21
    id: rf_cs_pin
    restore_mode: ALWAYS_ON

logger:
  level: VERBOSE

api:
  port: 6052

ota:

wifi:

remote_receiver:
  pin: 
    number: GPIO19
    inverted: False
  dump: all
  tolerance: 25%
  filter: 50us
  idle: 10ms
  buffer_size: 32kb

captive_portal:
