alias: Open window
description: ""
triggers:
  - trigger: time_pattern
    minutes: /10
conditions:
  - condition: and
    conditions:
      - condition: state
        entity_id: switch.guestroomlightsensor_toggle_automation_off_1_hr
        state: "off"
      - condition: numeric_state
        entity_id: sensor.guestroomlightsensor_ambient_light
        above: 50
actions:
  - device_id: ----------
    domain: button
    entity_id: ----------
    type: press
mode: single
